site_name: NotNadekoBot
repo_url: https://github.com/fearnlj01/DocTest
pages:
- Guides:
    - Windows Guide - Done: Windows Guide.md
    - Linux Guide - Done: Linux Guide.md
    - OSX Guide - Not Done: guides/OSX Guide.md
    - Upgrading from pre 1.0 - guides/Upgrading Guide.md

theme: readthedocs
